server:
  servlet:
    application-display-name:  AppIo Producer v2.102 18 Marzo 2022
  error:
    include-message: always
spring:
  datasource:
    url: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: 
    password: 

logging:
  file.name: ${catalina.base}/logs/appioproducer.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg{nolookups}%n"
    file: "%d [%t] %-5level %logger{36} - %msg{nolookups}%n"
  level:
    com.m2evorah: INFO
    org.springframework: INFO
    org.hibernate: INFO

appiogateway:
  url-base: http://localhost:8080/appiogateway
user-services:
  vbg:
    username: 
    password: 

cron:
  expression: '10 * * * * ?'