server:
  servlet:
    application-display-name:  AppIo Gateway v2.102 18 Marzo 2022 
  error:
    include-message: always
spring:
  datasource:
    url: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: 
    password: 
      
ioproxy:
  scope: am_application_scope, default
  authorization-uri: 
  token-uri: 
  
user-services:
  vbg:
    username: 
    password: 

developers-italia:
  server-endpoint-url: https://api.io.italia.it/api/v1
  
logging:
  file.name: ${catalina.base}/logs/appiogateway.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg{nolookups}%n"
    file: "%d [%t] %-5level %logger{36} - %msg{nolookups}%n"
  level:
    com.m2evorah: INFO
    org.springframework: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate: INFO

ud-connector:
  sandbox-endpoint-url: 
  
springdoc:
  packagesToScan: com.paevolution.appiogateway.web.controllers.api
  pathsToMatch: /messages, /messages/**

cron:
  expression: '0 * * ? * *'
  
  
