server:
  servlet:
    application-display-name:  AppIo Gateway v2.117 02 Febbraio 2024 
  error:
    include-message: always
spring:
  datasource:
    #url:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #username: 
    #password: 
    url: 
    driver-class-name: com.mysql.jdbc.Driver
    username: 
    password: 
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher   
  jpa:
    hibernate:
      use-new-id-generator-mappings: false   
ioproxy:
  scope: am_application_scope, default
  authorization-uri: 
  token-uri: 
  
user-services:
  vbg:
    username: 
    password: 

developers-italia:
  server-endpoint-url:
  
logging:
  file.name: ${catalina.base}/logs/appiogateway.log
  pattern:
#    console: "%d [%t] %-5level %logger{36} - %msg{nolookups}%n"
    file: "%d [%t] %-5level %logger{36} - %msg{nolookups}%n"
  level:
    com.paevolution: INFO
    com.m2evorah: WARN
    org.springframework: WARN
    org.springframework.jdbc.core.JdbcTemplate: WARN
    org.springframework.jdbc.core.StatementCreatorUtils: WARN
    org.hibernate: WARN

ud-connector:
  sandbox-endpoint-url: 
  
springdoc:
  packagesToScan: com.paevolution.appiogateway.web.controllers.api
  pathsToMatch: /messages, /messages/**

cron:
  expression: '0 * * ? * *'
  
  
